export const jobData = [
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    {
        companyTitle: "Microsoft",
        jobTitle: "Front end developer",
        postingDate: "10 August 2022",
        jobLocation: "Hadapsar, Pune",
        jobDescription: `A Front-End Developer is responsible for developing new user-facing features, determining the structure and design of web pages, building reusable codes, optimizing page loading times, and using a variety of markup languages to create the web pages.`,
        type: "Full-time",
    },
    
];